### ISSUE TITLE
Frontpanel design file format

### ISSUE THREAD

**Issue by gnbl** [74hc595/1-Bit-AVR-Synthesizer#1]
Could you export the front panel graphics file [frontpanel.graffle](https://github.com/74hc595/1-Bit-AVR-Synthesizer/blob/master/frontpanel.graffle) to SVG?

**Comment by 74hc595** [comment]
Just uploaded an SVG version. Thanks for the suggestion!

**Comment by gnbl** [comment]
Great, thank you!
